openapi: 3.0.3

info:
  title: Phrase API Reference
  version: 2.0.0
  description: 
    $ref: './intro.md'

  contact:
    name: Phrase Support
    url: https://developers.phrase.com/api/
    email: support@phrase.com

  x-logo:
    url: "https://developers.phrase.com/images/phrase-logo.png"
    backgroundColor: "#0091eb"
    altText: "Phrase"

  termsOfService: 'https://phrase.com/terms/'

  license: 
    name: MIT
    url: https://choosealicense.com/licenses/mit/

servers:
  - url: https://api.phrase.com/v2

security:
  - Token: []
  - Basic: []

tags:
  - name: Spaces
    description: Everything about Space

x-tagGroups:
  - name: Workflows
    tags:
      - Spaces

components:
  securitySchemes:
    Token:
      type: apiKey
      in: header
      name: Authorization
      description: Enter your token in the format **token TOKEN**
    Basic:
      type: http
      scheme: basic

  headers:
    $ref: "./headers.yaml"

  schemas:
    account:
      $ref: "./schemas/account.yaml#/account"
    project:
      $ref: "./schemas/project.yaml#/project"
    space:
      $ref: "./schemas/space.yaml#/space"
    errors:
      $ref: "./schemas/errors.yaml#/errors"

  parameters:
    $ref: "./parameters.yaml"

  responses:
    $ref: "./responses.yaml"

paths:
  $ref: "./paths.yaml"
